baseurl = "https://http://paulefrensa.rbind.io/"
languageCode = "en-us"
title = " Paul Efren..."
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = "Paul Efren notes..."
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
#[[menu.main]]
 #   name = "Subscribe"
  #  url = "/index.xml"

[params]
    description = "An space for R - DataScience for Biology..."
    footer = "&copy; PaulESA 2018 | [Github](https://github.com/PaulESantos) | [Twitter](https://twitter.com/PaulEfrenSantos) |Powered by the [Ivy theme](https://ivy.yihui.name/) for [Hugo](https://gohugo.io/)"
    
    
    
    
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  
  